added fragment
projectdiscovery/urlutil pull request #6
Opened 2022-05-31 21:41 UTC by LuitelSamikshya

This PR adds fragment support to stop url fragments being stripped.

2022-06-01 20:57 UTC, Mzack9999 requested changes
- [ ] Remove code related to https://github.com/projectdiscovery/urlutil/pull/2
- [ ] Review https://github.com/projectdiscovery/urlutil/pull/2, merge it into `dev`, then merge `dev` into this branch
- [ ] Please add a little test case related to Fragment parsing in `urlutil_test.go`

Notes: depends on https://github.com/projectdiscovery/urlutil/pull/2

2022-06-02 04:21 UTC, LuitelSamikshya commented on urlutil.go
> +	//fragment
Done

2022-06-02 04:21 UTC, LuitelSamikshya commented on urlutil.go
> +		// try to reparse without the request path
Done

2022-06-02 04:21 UTC, LuitelSamikshya commented on urlutil.go
> +	if u.Fragment != "" && u.RequestURI == "" {
Done

2022-06-03 14:40 UTC, Mzack9999 approved these changes

2022-06-03 14:41 UTC, merged